// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsQuickStartVpc.Inputs
{

    /// <summary>
    /// The list of Configurations in which to create subnets. You can specify availability
    /// zone with a private or a public subnet cidr block. You can also associated a private
    /// subnet with a dedicated network ACL.
    /// </summary>
    public sealed class AvailabilityZoneArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The availability zone name to deploy the subnet into
        /// </summary>
        [Input("availabilityZone", required: true)]
        public string AvailabilityZone { get; set; } = null!;

        /// <summary>
        /// CIDR block for a private subnet located in the specified availability zone
        /// </summary>
        [Input("privateSubnetACidr")]
        public string? PrivateSubnetACidr { get; set; }

        /// <summary>
        /// CIDR block for the associated private subnet (2) with a dedicated network ACL located in the specified availability zone. This subnet
        /// will only be created if `CreateAdditionalPrivateSubnets` is `true`.
        /// </summary>
        [Input("privateSubnetBCidr")]
        public string? PrivateSubnetBCidr { get; set; }

        /// <summary>
        /// CIDR block for the public subnet located in the specified availability zone
        /// </summary>
        [Input("publicSubnetCidr")]
        public string? PublicSubnetCidr { get; set; }

        public AvailabilityZoneArgs()
        {
        }
        public static new AvailabilityZoneArgs Empty => new AvailabilityZoneArgs();
    }
}
